#!/usr/bin/env python3

from pathlib import Path
import json


REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE_PATH = REPO_ROOT / "examples" / "default-config.toml"
OUTPUT_PATH = REPO_ROOT / "src" / "pkjs" / "default-config.generated.js"


def main() -> int:
  toml = SOURCE_PATH.read_text(encoding="utf-8")
  output = (
    "// Generated from examples/default-config.toml by "
    "scripts/generate_default_config_js.py.\n"
    "// Do not edit this file directly.\n"
    f"module.exports = {json.dumps(toml)};\n"
  )
  OUTPUT_PATH.write_text(output, encoding="utf-8")
  return 0


if __name__ == "__main__":
  raise SystemExit(main())
