#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

const { parseTimerToml } = require("../src/pkjs/timer-config");

const repoRoot = path.resolve(__dirname, "..");
const sourcePath = path.join(repoRoot, "examples", "default-config.toml");
const outputPath = path.join(repoRoot, "src", "c", "default_config.generated.c");

function cString(value) {
  return JSON.stringify(String(value));
}

function cBool(value) {
  return value ? "true" : "false";
}

function cU64(value) {
  return `${String(value)}ULL`;
}

function emitVibe(step) {
  return [
    "{",
    `  .intensity = ${step.intensity},`,
    `  .duration_ms = ${step.duration},`,
    `  .delay_ms = ${step.delay},`,
    "}",
  ].join("\n");
}

function emitWarning(warn) {
  const lines = [
    "{",
    `  .time_before_end_ms = ${cU64(warn.timeBeforeEndMs)},`,
    `  .vibe_count = ${warn.vibrate.length},`,
  ];
  if (warn.vibrate.length) {
    lines.push("  .vibes = {");
    warn.vibrate.forEach(function(step) {
      lines.push(indent(emitVibe(step), 4) + ",");
    });
    lines.push("  },");
  }
  lines.push("}");
  return lines.join("\n");
}

function emitSegment(segment) {
  const lines = [
    "{",
    `  .name = ${cString(segment.name)},`,
    `  .hint = ${cString(segment.hint)},`,
    `  .duration_ms = ${cU64(segment.durationMs)},`,
    `  .vibe_count = ${segment.vibrate.length},`,
    `  .warn_count = ${segment.warnAt.length},`,
  ];
  if (segment.vibrate.length) {
    lines.push("  .vibes = {");
    segment.vibrate.forEach(function(step) {
      lines.push(indent(emitVibe(step), 4) + ",");
    });
    lines.push("  },");
  }
  if (segment.warnAt.length) {
    lines.push("  .warns = {");
    segment.warnAt.forEach(function(warn) {
      lines.push(indent(emitWarning(warn), 4) + ",");
    });
    lines.push("  },");
  }
  lines.push("}");
  return lines.join("\n");
}

function emitUpAction(action, fieldName) {
  return [
    `  .${fieldName} = {`,
    `    .kind = ${action.kind},`,
    `    .duration_ms = ${cU64(action.durationMs)},`,
    "  },",
  ].join("\n");
}

function indent(text, spaces) {
  const prefix = " ".repeat(spaces);
  return text.split("\n").map(function(line) {
    return line ? prefix + line : line;
  }).join("\n");
}

function emitTimer(timer, index) {
  const lines = [
    "{",
    `  .name = ${cString(timer.name)},`,
    `  .repeat = ${cBool(timer.repeat)},`,
    `  .iterations_enabled = ${cBool(timer.iterationsEnabled)},`,
    `  .must_acknowledge = ${cBool(timer.mustAcknowledge)},`,
    `  .stopwatch = ${cBool(timer.stopwatch)},`,
    `  .stopwatch_only = ${cBool(timer.stopwatchOnly)},`,
    emitUpAction(timer.onPressUp, "on_press_up"),
    emitUpAction(timer.onLongPressUp, "on_long_press_up"),
    emitUpAction(timer.onLongPressSelect, "on_long_press_select"),
    `  .iterations = ${timer.iterations},`,
    `  .repeat_pattern_delay_ms = ${timer.repeatPatternDelay},`,
    `  .acknowledge_alert_duration_s = ${timer.acknowledgeAlertDuration},`,
    `  .finish_vibe_count = ${timer.finishVibrate.length},`,
    `  .segment_count = ${timer.pattern.length},`,
    `  .trigger_kind = ${timer.trigger.kind},`,
    `  .trigger_from = ${timer.trigger.from},`,
    `  .trigger_to = ${timer.trigger.to},`,
  ];
  if (timer.finishVibrate.length) {
    lines.push("  .finish_vibes = {");
    timer.finishVibrate.forEach(function(step) {
      lines.push(indent(emitVibe(step), 4) + ",");
    });
    lines.push("  },");
  }
  lines.push(`  .segments = (TimerSegment *)s_default_timer_${index}_segments,`);
  lines.push("}");
  return lines.join("\n");
}

function buildOutput(config) {
  const lines = [
    "// Generated from examples/default-config.toml by scripts/generate_default_config_c.js.",
    "// Do not edit this file directly.",
    "",
    '#include "default_config_generated.h"',
    "",
    "#include <stdlib.h>",
    "#include <string.h>",
    "",
  ];

  config.timers.forEach(function(timer, timerIndex) {
    lines.push(`static const TimerSegment s_default_timer_${timerIndex}_segments[] = {`);
    timer.pattern.forEach(function(segment) {
      lines.push(indent(emitSegment(segment), 2) + ",");
    });
    lines.push("};");
    lines.push("");
  });

  lines.push("static const TimerDefinition s_default_timers[] = {");
  config.timers.forEach(function(timer, timerIndex) {
    lines.push(indent(emitTimer(timer, timerIndex), 2) + ",");
  });
  lines.push("};");
  lines.push("");
  lines.push("bool default_config_generated_build(TimerConfig *config) {");
  lines.push("  if (!config) {");
  lines.push("    return false;");
  lines.push("  }");
  lines.push("");
  lines.push("  memset(config, 0, sizeof(*config));");
  lines.push("  config->version = CONFIG_VERSION;");
  lines.push("  config->timer_count = ARRAY_LENGTH(s_default_timers);");
  lines.push("  config->timer_capacity = ARRAY_LENGTH(s_default_timers);");
  lines.push("  config->icons_enabled = true;");
  lines.push("  config->background_enabled = true;");
  lines.push("  config->timer_accent_enabled = true;");
  lines.push("  config->timers = calloc(config->timer_count, sizeof(TimerDefinition));");
  lines.push("  if (!config->timers) {");
  lines.push("    memset(config, 0, sizeof(*config));");
  lines.push("    return false;");
  lines.push("  }");
  lines.push("");
  lines.push("  for (uint8_t i = 0; i < config->timer_count; ++i) {");
  lines.push("    config->timers[i] = s_default_timers[i];");
  lines.push("    config->timers[i].segments = NULL;");
  lines.push("    if (config->timers[i].segment_count == 0) {");
  lines.push("      continue;");
  lines.push("    }");
  lines.push("    config->timers[i].segments = calloc(config->timers[i].segment_count, sizeof(TimerSegment));");
  lines.push("    if (!config->timers[i].segments) {");
  lines.push("      for (uint8_t timer_index = 0; timer_index <= i; ++timer_index) {");
  lines.push("        free(config->timers[timer_index].segments);");
  lines.push("      }");
  lines.push("      free(config->timers);");
  lines.push("      memset(config, 0, sizeof(*config));");
  lines.push("      return false;");
  lines.push("    }");
  lines.push("    memcpy(config->timers[i].segments, s_default_timers[i].segments,");
  lines.push("           sizeof(TimerSegment) * config->timers[i].segment_count);");
  lines.push("  }");
  lines.push("");
  lines.push("  return true;");
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

function main() {
  const toml = fs.readFileSync(sourcePath, "utf8");
  const config = parseTimerToml(toml);
  fs.writeFileSync(outputPath, buildOutput(config), "utf8");
}

main();
