// Generated from examples/default-config.toml by scripts/generate_default_config_c.js.
// Do not edit this file directly.

#include "default_config_generated.h"

#include <stdlib.h>
#include <string.h>

static const TimerSegment s_default_timer_0_segments[] = {
  {
    .name = "",
    .hint = "",
    .duration_ms = 60000ULL,
    .vibe_count = 0,
    .warn_count = 0,
  },
};

static const TimerSegment s_default_timer_1_segments[] = {
  {
    .name = "",
    .hint = "",
    .duration_ms = 600000ULL,
    .vibe_count = 0,
    .warn_count = 0,
  },
};

static const TimerSegment s_default_timer_2_segments[] = {
  {
    .name = "",
    .hint = "",
    .duration_ms = 1200000ULL,
    .vibe_count = 0,
    .warn_count = 0,
  },
};

static const TimerSegment s_default_timer_3_segments[] = {
  {
    .name = "",
    .hint = "",
    .duration_ms = 9007199254740991ULL,
    .vibe_count = 0,
    .warn_count = 0,
  },
};

static const TimerDefinition s_default_timers[] = {
  {
    .name = "1 Min",
    .repeat = false,
    .iterations_enabled = false,
    .must_acknowledge = false,
    .stopwatch = false,
    .stopwatch_only = false,
    .on_press_up = {
      .kind = 3,
      .duration_ms = 60000ULL,
    },
    .on_long_press_up = {
      .kind = 3,
      .duration_ms = 30000ULL,
    },
    .on_long_press_select = {
      .kind = 2,
      .duration_ms = 0ULL,
    },
    .iterations = 0,
    .repeat_pattern_delay_ms = 500,
    .acknowledge_alert_duration_s = 12,
    .finish_vibe_count = 2,
    .segment_count = 1,
    .trigger_kind = 1,
    .trigger_from = 2,
    .trigger_to = 0,
    .finish_vibes = {
      {
        .intensity = 2,
        .duration_ms = 500,
        .delay_ms = 200,
      },
      {
        .intensity = 2,
        .duration_ms = 500,
        .delay_ms = 200,
      },
    },
    .segments = (TimerSegment *)s_default_timer_0_segments,
  },
  {
    .name = "10 Min",
    .repeat = false,
    .iterations_enabled = false,
    .must_acknowledge = false,
    .stopwatch = false,
    .stopwatch_only = false,
    .on_press_up = {
      .kind = 3,
      .duration_ms = 300000ULL,
    },
    .on_long_press_up = {
      .kind = 3,
      .duration_ms = 60000ULL,
    },
    .on_long_press_select = {
      .kind = 2,
      .duration_ms = 0ULL,
    },
    .iterations = 0,
    .repeat_pattern_delay_ms = 500,
    .acknowledge_alert_duration_s = 12,
    .finish_vibe_count = 2,
    .segment_count = 1,
    .trigger_kind = 1,
    .trigger_from = 2,
    .trigger_to = 0,
    .finish_vibes = {
      {
        .intensity = 2,
        .duration_ms = 500,
        .delay_ms = 200,
      },
      {
        .intensity = 2,
        .duration_ms = 500,
        .delay_ms = 200,
      },
    },
    .segments = (TimerSegment *)s_default_timer_1_segments,
  },
  {
    .name = "20 Min",
    .repeat = false,
    .iterations_enabled = false,
    .must_acknowledge = false,
    .stopwatch = false,
    .stopwatch_only = false,
    .on_press_up = {
      .kind = 3,
      .duration_ms = 600000ULL,
    },
    .on_long_press_up = {
      .kind = 3,
      .duration_ms = 300000ULL,
    },
    .on_long_press_select = {
      .kind = 2,
      .duration_ms = 0ULL,
    },
    .iterations = 0,
    .repeat_pattern_delay_ms = 500,
    .acknowledge_alert_duration_s = 12,
    .finish_vibe_count = 2,
    .segment_count = 1,
    .trigger_kind = 1,
    .trigger_from = 2,
    .trigger_to = 0,
    .finish_vibes = {
      {
        .intensity = 2,
        .duration_ms = 500,
        .delay_ms = 200,
      },
      {
        .intensity = 2,
        .duration_ms = 500,
        .delay_ms = 200,
      },
    },
    .segments = (TimerSegment *)s_default_timer_2_segments,
  },
  {
    .name = "Stopwatch",
    .repeat = false,
    .iterations_enabled = false,
    .must_acknowledge = false,
    .stopwatch = true,
    .stopwatch_only = true,
    .on_press_up = {
      .kind = 0,
      .duration_ms = 0ULL,
    },
    .on_long_press_up = {
      .kind = 0,
      .duration_ms = 0ULL,
    },
    .on_long_press_select = {
      .kind = 2,
      .duration_ms = 0ULL,
    },
    .iterations = 0,
    .repeat_pattern_delay_ms = 500,
    .acknowledge_alert_duration_s = 12,
    .finish_vibe_count = 0,
    .segment_count = 1,
    .trigger_kind = 2,
    .trigger_from = 2,
    .trigger_to = 4,
    .segments = (TimerSegment *)s_default_timer_3_segments,
  },
};

bool default_config_generated_build(TimerConfig *config) {
  if (!config) {
    return false;
  }

  memset(config, 0, sizeof(*config));
  config->version = CONFIG_VERSION;
  config->timer_count = ARRAY_LENGTH(s_default_timers);
  config->timer_capacity = ARRAY_LENGTH(s_default_timers);
  config->icons_enabled = true;
  config->background_enabled = true;
  config->timer_accent_enabled = true;
  config->timers = calloc(config->timer_count, sizeof(TimerDefinition));
  if (!config->timers) {
    memset(config, 0, sizeof(*config));
    return false;
  }

  for (uint8_t i = 0; i < config->timer_count; ++i) {
    config->timers[i] = s_default_timers[i];
    config->timers[i].segments = NULL;
    if (config->timers[i].segment_count == 0) {
      continue;
    }
    config->timers[i].segments = calloc(config->timers[i].segment_count, sizeof(TimerSegment));
    if (!config->timers[i].segments) {
      for (uint8_t timer_index = 0; timer_index <= i; ++timer_index) {
        free(config->timers[timer_index].segments);
      }
      free(config->timers);
      memset(config, 0, sizeof(*config));
      return false;
    }
    memcpy(config->timers[i].segments, s_default_timers[i].segments,
           sizeof(TimerSegment) * config->timers[i].segment_count);
  }

  return true;
}
